default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV["DATABASE_USERNAME"] || Rails.application.credentials.dig(:mysql, Rails.env.to_sym, :username) %>
  password: <%= ENV["DATABASE_PASSWORD"] || Rails.application.credentials.dig(:mysql, Rails.env.to_sym, :password) %>
<% if ENV["DATABASE_HOST"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: <%= ENV.fetch("DATABASE_PORT", 3306) %>
<% else %>
  socket: /var/lib/mysql/mysql.sock
<% end %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "ffxiv_collect_development") %>

test:
  <<: *default
  database: ffxiv_collect_test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "ffxiv_collect_production") %>
